Repository layer
lucky-pocket/luckyPocket-back pull request #13
Opened 2023-10-21 14:42 UTC by BLoHny

# summary
Domain 관련 Repository를 정의했습니다
# changes
- User 에 Repository추가
- Auth에 Repository추가
- Pocket에 Repository추가
- Notice에 Repository추가

close #12

2023-10-21 15:03 UTC, onee-only requested changes

2023-10-21 15:03 UTC, onee-only commented on internal/domain/auth.go
> +	ExistByRefreshToken(ctx context.Context, refreshToken *string) (bool, error)
string에 포인터를 넣으신 이유가 따로 있나요?

2023-10-21 15:03 UTC, onee-only commented on internal/domain/auth.go
> +type AuthRepository interface {
AuthRepository는 어떤 작업을 위해서 만들었나요?

2023-10-21 15:03 UTC, onee-only commented on internal/domain/notification.go
> +	Create(ctx context.Context, notice *Notice) error
Create가 따로 있는 이유가 있을까요?
Notice는 따로 모아서 한번에 생성하기로 했으니 그 점 참고하는 게  좋을 것 같습니다.

2023-10-21 15:03 UTC, onee-only commented on internal/domain/notification.go
> +	FindAllByUser(ctx context.Context, user *User) error
FindAllByUser보다는 FindAllByUserID가 더 간단할 것 같습니다. 굳이 user struct를 만들어 넣을 필요는 없으니까요.

2023-10-21 15:03 UTC, onee-only commented on internal/domain/notification.go
> +	FindAllByUser(ctx context.Context, user *User) error
FindAll이 output을 주지 않습니다. 수정해주세요.

2023-10-21 15:03 UTC, onee-only commented on internal/domain/notification.go
> +	FindByID(ctx context.Context, noticeId *uint64) error
noticeId에 포인터를 단 이유가 있을까요? 여기도 마찬가지로 output이 없습니다.

2023-10-21 15:03 UTC, onee-only commented on internal/domain/pocket.go
> +	FindByID(ctx context.Context, pocketId *uint64) error
output 추가해주세요

2023-10-21 15:03 UTC, onee-only commented on internal/domain/pocket.go
> +	FindAllByUser(ctx context.Context, user *User) error
pagination이 필요합니다. 그리고 UserID로 바꿔주세요

2023-10-21 15:03 UTC, onee-only commented on internal/domain/pocket.go
> +	FindAll(ctx context.Context) error
이건 어디에 사용하는 건지 알 수 있을까요?

2023-10-21 15:03 UTC, onee-only commented on internal/domain/user.go
> +	FindByID(ctx context.Context, userId *uint64) error
output 추가해주세요. userID 포인터 빼주세요.

2023-10-21 15:03 UTC, onee-only commented on internal/domain/user.go
> +	Exists(ctx context.Context, userId *uint64) (bool, error)
userID pointer 빼주세요

2023-10-21 15:04 UTC, onee-only commented
linter가 잡아내는 컨벤션도 지켜주세요

2023-10-21 15:16 UTC, onee-only commented
아 깜빡하고 말 못했는데 Pocket struct에 Sender랑 Receiver 필드에 달려있는 ID 제거해주세요. struct pointer니 그렇게 하는 게 맞다고 생각합니다.

2023-10-21 15:23 UTC, BLoHny commented on internal/domain/auth.go
> +type AuthRepository interface {
로그아웃 한 유저를 담아두는 repository인데 이름을 BlackListRepository로 바꾸는게 나을 것 같습니다

2023-10-21 16:08 UTC, BLoHny commented on internal/domain/auth.go
> +	ExistByRefreshToken(ctx context.Context, refreshToken *string) (bool, error)
이미 저장되있는 토큰을 찾는것이므로 생각해보니 nil을 허용하면 안될것 같습니다. 수정하겠습니다

2023-10-21 18:41 UTC, BLoHny commented on internal/domain/pocket.go
> +	FindAll(ctx context.Context) error
필터없는 전체 불러오기 화면을 생각했었는데 생각 해보니 필요없을 것 같습니다. 삭제하겠습니다

2023-10-22 01:44 UTC, onee-only commented on internal/domain/auth.go
> +type AuthRepository interface {
넵 그게 좋을 것 같습니다.

2023-10-22 01:44 UTC, onee-only commented on internal/domain/pocket.go
> +	FindByID(ctx context.Context, pocketID *uint64) (pocket *Pocket, err error)
포인터 벗겨주세요

2023-10-22 01:44 UTC, onee-only commented on internal/domain/pocket.go
> +	FindAllByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
pagination이 들어가니 더이상 FindAll이 아닐 것 같다고 생각하는데 어떻게 생각하시나요?

2023-10-22 01:45 UTC, onee-only commented on internal/domain/auth.go
> +	ExistByRefreshToken(ctx context.Context, refreshToken *string) (bool, error)
그런 뜻은 아니었고 string 자체가 reference라서 굳이 포인터가 필요 없다는 이야기였어요

2023-10-22 01:48 UTC, onee-only commented
repository의 return 값들이 named와 unnamed가 섞여 있습니다. 하나로 통일시키는 것이 좋을 것 같아요!

2023-10-22 01:52 UTC, onee-only commented on internal/domain/auth.go
> +	ExistByRefreshToken(ctx context.Context, refreshToken string) (bool, error)
만약 저희가 이 BlackListRepository가 refreshToken을 관리한다는 것을 알면 굳이 한번 더 명시할 필요는 없을 것 같아요!
```suggestion
	Exists(ctx context.Context, refreshToken string) (bool, error)
```

2023-10-22 01:52 UTC, onee-only commented on internal/domain/auth.go
> +}
Save같은 메서드도 있어야 할 것 같습니다

2023-10-22 03:23 UTC, BLoHny commented on internal/domain/pocket.go
> +	FindAllByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
FindPocketListByUserID로 수정하는게 나을까요?

2023-10-22 04:30 UTC, onee-only commented on internal/domain/pocket.go
> +	FindAllByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
FindListByUserID는 어떤가요? 너무 길어지는 것 같아서요

2023-10-22 04:31 UTC, BLoHny commented on internal/domain/pocket.go
> +	FindAllByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
그게 더 좋은것같습니다. 수정하겠습니다

2023-10-22 04:33 UTC, onee-only commented on internal/domain/pocket.go
> +	FindListByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
여기 unnamed return으로 바꿔주실 수 있나요? 다른 인터페이스에선 안 되어 있어서요

2023-10-22 04:39 UTC, onee-only commented on internal/domain/pocket.go
> +	FindListByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
@BLoHny

2023-10-22 04:42 UTC, BLoHny commented on internal/domain/pocket.go
> +	FindListByUserID(ctx context.Context, userID uint64, offset, limit int) (pocketList []*Pocket, err error)
수정했습니다

2023-10-22 04:44 UTC, onee-only approved these changes

2023-10-22 04:44 UTC, merged